export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CAREER_REQUEST = "CAREER_REQUEST";
export const CAREER_SUCCESS = "CAREER_SUCCESS";
export const CAREER_ERROR = "CAREER_ERROR";

export const CAREER_BYID_REQUEST = "CAREER_BYID_REQUEST";
export const CAREER_BYID_SUCCESS = "CAREER_BYID_SUCCESS";
export const CAREER_BYID_ERROR = "CAREER_BYID_ERROR";

export const UNI_REQUEST = "UNI_REQUEST";
export const UNI_SUCCESS = "UNI_SUCCESS";
export const UNI_ERROR = "UNI_ERROR";
export const UNI_BYID_SUCCESS = "UNI_BYID_SUCCESS";

export const MEDIA_REQUEST = "MEDIA_REQUEST";
export const MEDIA_SUCCESS = "MEDIA_SUCCESS";
export const MEDIA_ERROR = "MEDIA_ERROR";

export const DELETE_SUCCESS = "DELETE_SUCCESS";
